import { Injectable } from '@angular/core';
import { Observable, of, delay } from 'rxjs';
import { ProductResponse, ProductListResponse } from '../models/product.model';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private dummyProducts: ProductResponse[] = [
    {
      id: '1f8eef1aeef3cbfaad2f0ec207945d9f',
      approved: true,
      archived: false,
      productCode: 75984627,
      batchRequestId: null,
      supplierId: 123456,
      createDateTime: 1593680142092,
      lastUpdateDate: 1594382124384,
      gender: 'Female',
      brand: 'Atlas Premium',
      barcode: '8690123456789',
      title: 'Long Wavy Blonde Wig - Natural Look',
      categoryName: 'Wigs',
      productMainId: 'PM001',
      description:
        'Premium quality synthetic wig with natural wavy texture. Perfect for everyday wear or special occasions. Heat resistant up to 180°C.',
      stockUnitType: 'PIECE',
      quantity: 15,
      listPrice: 299.99,
      salePrice: 249.99,
      vatRate: 20,
      dimensionalWeight: 0.5,
      stockCode: 'STK-BLONDE-001',
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: 'LOT2024001',
      deliveryOption: {
        deliveryDuration: 3,
        fastDeliveryType: 'FAST_DELIVERY',
      },
      images: [
        {
          url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500',
        },
        {
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 1,
          attributeValue: 'Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 4,
          attributeValue: 'Wavy',
        },
      ],
      platformListingId: 'PLT001',
      stockId: 'STK001',
      hasActiveCampaign: true,
      locked: false,
      productContentId: 1001,
      pimCategoryId: 501,
      brandId: 201,
      version: 1,
      color: 'Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/1f8eef1aeef3cbfaad2f0ec207945d9f',
    },
    {
      id: '2a9fef2beff4dcgbbae3f1fd318056e0g',
      approved: true,
      archived: false,
      productCode: 75984628,
      supplierId: 123456,
      createDateTime: 1593680142093,
      lastUpdateDate: 1594382124385,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Curly Red Hair Wig - Vibrant',
      categoryName: 'Wigs',
      description:
        'Beautiful curly red wig with natural movement. Made from high-quality synthetic fibers that mimic real hair.',
      quantity: 8,
      listPrice: 349.99,
      salePrice: 299.99,
      vatRate: 20,
      stockCode: 'STK-RED-001',
      deliveryOption: {
        deliveryDuration: 5,
        fastDeliveryType: null,
      },
      images: [
        {
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 5,
          attributeValue: 'Red',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (22 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 5,
          attributeValue: 'Curly',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Red',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/2a9fef2beff4dcgbbae3f1fd318056e0g',
    },
    {
      id: '3b0gfg3cffg5edhccbf4g2ge429167f1h',
      approved: true,
      archived: false,
      productCode: 75984629,
      supplierId: 123456,
      createDateTime: 1593680142094,
      lastUpdateDate: 1594382124386,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Straight Black Wig - Classic Elegance',
      categoryName: 'Wigs',
      description:
        'Classic straight black wig for a timeless look. Perfect for professional settings or formal events.',
      quantity: 20,
      listPrice: 279.99,
      salePrice: 229.99,
      vatRate: 20,
      stockCode: 'STK-BLACK-001',
      deliveryOption: {
        deliveryDuration: 2,
        fastDeliveryType: 'SAME_DAY_SHIPPING',
      },
      images: [
        {
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 6,
          attributeValue: 'Black',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 3,
          attributeValue: 'Medium (18 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 6,
          attributeValue: 'Straight',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Black',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/3b0gfg3cffg5edhccbf4g2ge429167f1h',
    },
    {
      id: '4c1hgh4dggg6feiddcg5h3hf530278g2i',
      approved: true,
      archived: false,
      productCode: 75984630,
      supplierId: 123456,
      createDateTime: 1593680142095,
      lastUpdateDate: 1594382124387,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Platinum Blonde Straight Wig',
      categoryName: 'Wigs',
      description:
        'Stunning platinum blonde straight wig. Ultra-lightweight and comfortable for all-day wear.',
      quantity: 12,
      listPrice: 379.99,
      salePrice: 329.99,
      vatRate: 20,
      stockCode: 'STK-PLATINUM-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 7,
          attributeValue: 'Platinum Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (26 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 6,
          attributeValue: 'Straight',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Platinum Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/4c1hgh4dggg6feiddcg5h3hf530278g2i',
    },
    {
      id: '5d2ihi5ehhh7gfjeedh6i4ig641389h3j',
      approved: true,
      archived: false,
      productCode: 75984631,
      supplierId: 123456,
      createDateTime: 1593680142096,
      lastUpdateDate: 1594382124388,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Brunette Wavy Wig - Natural Brown',
      categoryName: 'Wigs',
      description:
        'Natural brunette wavy wig with subtle highlights. Perfect for a sophisticated everyday look.',
      quantity: 18,
      listPrice: 289.99,
      salePrice: 239.99,
      vatRate: 20,
      stockCode: 'STK-BRUNETTE-001',
      deliveryOption: {
        deliveryDuration: 4,
        fastDeliveryType: 'FAST_DELIVERY',
      },
      images: [
        {
          url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 8,
          attributeValue: 'Brunette',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 4,
          attributeValue: 'Wavy',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Brunette',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/5d2ihi5ehhh7gfjeedh6i4ig641389h3j',
    },
    {
      id: '6e3jij6fiii8hgkffeej7j5jh752490i4k',
      approved: true,
      archived: false,
      productCode: 75984632,
      supplierId: 123456,
      createDateTime: 1593680142097,
      lastUpdateDate: 1594382124389,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Auburn Curly Wig - Warm Tones',
      categoryName: 'Wigs',
      description:
        'Warm auburn curly wig with rich red-brown tones. Adds warmth and dimension to your look.',
      quantity: 10,
      listPrice: 329.99,
      salePrice: 279.99,
      vatRate: 20,
      stockCode: 'STK-AUBURN-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 9,
          attributeValue: 'Auburn',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (22 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 5,
          attributeValue: 'Curly',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Auburn',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/6e3jij6fiii8hgkffeej7j5jh752490i4k',
    },
    {
      id: '7f4kjk7gjjj9ihlggffk8k6ki863591j5l',
      approved: true,
      archived: false,
      productCode: 75984633,
      supplierId: 123456,
      createDateTime: 1593680142098,
      lastUpdateDate: 1594382124390,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Ombre Blonde to Brown Wig',
      categoryName: 'Wigs',
      description:
        'Trendy ombre wig transitioning from blonde to brown. Modern and stylish for fashion-forward individuals.',
      quantity: 7,
      listPrice: 399.99,
      salePrice: 349.99,
      vatRate: 20,
      stockCode: 'STK-OMBRE-001',
      deliveryOption: {
        deliveryDuration: 6,
        fastDeliveryType: null,
      },
      images: [
        {
          url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 10,
          attributeValue: 'Ombre Blonde-Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 7,
          attributeValue: 'Ombre',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Ombre',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/7f4kjk7gjjj9ihlggffk8k6ki863591j5l',
    },
    {
      id: '8g5lkl8hkkk0jimhhggl9l7lj974602k6m',
      approved: true,
      archived: false,
      productCode: 75984634,
      supplierId: 123456,
      createDateTime: 1593680142099,
      lastUpdateDate: 1594382124391,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Short Bob Wig - Dark Brown',
      categoryName: 'Wigs',
      description:
        'Chic short bob wig in dark brown. Perfect for a professional and polished appearance.',
      quantity: 14,
      listPrice: 249.99,
      salePrice: 199.99,
      vatRate: 20,
      stockCode: 'STK-BOB-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 11,
          attributeValue: 'Dark Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 4,
          attributeValue: 'Short (12 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 8,
          attributeValue: 'Bob',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Dark Brown',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/8g5lkl8hkkk0jimhhggl9l7lj974602k6m',
    },
    {
      id: '9h6mlm9illl1kjniiihm0m8mk085713l7n',
      approved: true,
      archived: false,
      productCode: 75984635,
      supplierId: 123456,
      createDateTime: 1593680142100,
      lastUpdateDate: 1594382124392,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Straight Wig - Honey Blonde',
      categoryName: 'Wigs',
      description:
        'Beautiful honey blonde straight wig. Natural-looking color with smooth, silky texture.',
      quantity: 16,
      listPrice: 319.99,
      salePrice: 269.99,
      vatRate: 20,
      stockCode: 'STK-HONEY-001',
      deliveryOption: {
        deliveryDuration: 3,
        fastDeliveryType: 'FAST_DELIVERY',
      },
      images: [
        {
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 12,
          attributeValue: 'Honey Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (26 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 6,
          attributeValue: 'Straight',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Honey Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/9h6mlm9illl1kjniiihm0m8mk085713l7n',
    },
    {
      id: '0i7nmn0jmmm2mlojjjin1n9nl196824m8o',
      approved: true,
      archived: false,
      productCode: 75984636,
      supplierId: 123456,
      createDateTime: 1593680142101,
      lastUpdateDate: 1594382124393,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Pixie Cut Wig - Black',
      categoryName: 'Wigs',
      description:
        'Bold pixie cut wig in classic black. Low maintenance and perfect for active lifestyles.',
      quantity: 11,
      listPrice: 219.99,
      salePrice: 179.99,
      vatRate: 20,
      stockCode: 'STK-PIXIE-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 6,
          attributeValue: 'Black',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 5,
          attributeValue: 'Very Short (6 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 9,
          attributeValue: 'Pixie',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Black',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/0i7nmn0jmmm2mlojjjin1n9nl196824m8o',
    },
    {
      id: '1a8ono1knnn3nmpokkkjo2o0om207935n9p',
      approved: true,
      archived: false,
      productCode: 75984637,
      supplierId: 123456,
      createDateTime: 1593680142102,
      lastUpdateDate: 1594382124394,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Curly Wig - Caramel Brown',
      categoryName: 'Wigs',
      description:
        'Rich caramel brown curly wig with natural bounce and movement. Perfect for adding volume and texture.',
      quantity: 13,
      listPrice: 339.99,
      salePrice: 289.99,
      vatRate: 20,
      stockCode: 'STK-CARAMEL-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 13,
          attributeValue: 'Caramel Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 5,
          attributeValue: 'Curly',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Caramel Brown',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/1a8ono1knnn3nmpokkkjo2o0om207935n9p',
    },
    {
      id: '2b9pop2looo4onqplllkp3p1pn318046o0q',
      approved: true,
      archived: false,
      productCode: 75984638,
      supplierId: 123456,
      createDateTime: 1593680142103,
      lastUpdateDate: 1594382124395,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Wavy Blonde Hair Color - Permanent Dye',
      categoryName: 'Hair Colors',
      description:
        'Permanent hair dye in beautiful blonde shade. Long-lasting color with conditioning formula.',
      quantity: 25,
      listPrice: 89.99,
      salePrice: 69.99,
      vatRate: 20,
      stockCode: 'STK-DYE-BLONDE-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 1,
          attributeValue: 'Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 10,
          attributeValue: 'Permanent',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Blonde',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/2b9pop2looo4onqplllkp3p1pn318046o0q',
    },
    {
      id: '3c0qpq3mppp5porqmmmmlq4q2qo429157p1r',
      approved: true,
      archived: false,
      productCode: 75984639,
      supplierId: 123456,
      createDateTime: 1593680142104,
      lastUpdateDate: 1594382124396,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Red Hair Color - Vibrant Shade',
      categoryName: 'Hair Colors',
      description:
        'Vibrant red permanent hair dye. Bold and eye-catching color that lasts for weeks.',
      quantity: 20,
      listPrice: 94.99,
      salePrice: 74.99,
      vatRate: 20,
      stockCode: 'STK-DYE-RED-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 5,
          attributeValue: 'Red',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 10,
          attributeValue: 'Permanent',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Red',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/3c0qpq3mppp5porqmmmmlq4q2qo429157p1r',
    },
    {
      id: '4d1rqr4nqqq6qpsrnnnnmr5r3rp530268q2s',
      approved: true,
      archived: false,
      productCode: 75984640,
      supplierId: 123456,
      createDateTime: 1593680142105,
      lastUpdateDate: 1594382124397,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Black Hair Color - Deep Shine',
      categoryName: 'Hair Colors',
      description:
        'Deep black permanent hair dye with shine-enhancing formula. Perfect for covering grays.',
      quantity: 30,
      listPrice: 79.99,
      salePrice: 59.99,
      vatRate: 20,
      stockCode: 'STK-DYE-BLACK-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 6,
          attributeValue: 'Black',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 10,
          attributeValue: 'Permanent',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Black',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/4d1rqr4nqqq6qpsrnnnnmr5r3rp530268q2s',
    },
    {
      id: '5e2srs5orrr7rqtsoooons6s4sq641379r3t',
      approved: true,
      archived: false,
      productCode: 75984641,
      supplierId: 123456,
      createDateTime: 1593680142106,
      lastUpdateDate: 1594382124398,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Brunette Hair Color - Natural Brown',
      categoryName: 'Hair Colors',
      description:
        'Natural brunette shade permanent hair dye. Rich brown color with warm undertones.',
      quantity: 22,
      listPrice: 87.99,
      salePrice: 67.99,
      vatRate: 20,
      stockCode: 'STK-DYE-BRUNETTE-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 8,
          attributeValue: 'Brunette',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 10,
          attributeValue: 'Permanent',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Brunette',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/5e2srs5orrr7rqtsoooons6s4sq641379r3t',
    },
    {
      id: '6f3tst6psss8srutpppppt7t5tr752480s4u',
      approved: true,
      archived: false,
      productCode: 75984642,
      supplierId: 123456,
      createDateTime: 1593680142107,
      lastUpdateDate: 1594382124399,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Layered Wavy Wig - Medium Brown',
      categoryName: 'Wigs',
      description:
        'Stylish layered wavy wig in medium brown. Adds dimension and movement to your look.',
      quantity: 9,
      listPrice: 359.99,
      salePrice: 309.99,
      vatRate: 20,
      stockCode: 'STK-LAYERED-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 14,
          attributeValue: 'Medium Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 10,
          attributeValue: 'Layered Wavy',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Medium Brown',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/6f3tst6psss8srutpppppt7t5tr752480s4u',
    },
    {
      id: '7g4utu7qttt9tvsuqqqqqu8u6us863591t5v',
      approved: true,
      archived: false,
      productCode: 75984643,
      supplierId: 123456,
      createDateTime: 1593680142108,
      lastUpdateDate: 1594382124400,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Highlights Hair Color Kit - Blonde',
      categoryName: 'Hair Colors',
      description:
        'Professional highlighting kit for blonde highlights. Easy to use at home.',
      quantity: 18,
      listPrice: 119.99,
      salePrice: 99.99,
      vatRate: 20,
      stockCode: 'STK-HIGHLIGHTS-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 1,
          attributeValue: 'Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 12,
          attributeValue: 'Highlights Kit',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 13,
          attributeValue: 'Full Kit',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Blonde',
      size: 'Full Kit',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/7g4utu7qttt9tvsuqqqqqu8u6us863591t5v',
    },
    {
      id: '8h5vuv8ruuu0uwtvrrrrrv9v7vt974602u6w',
      approved: true,
      archived: false,
      productCode: 75984644,
      supplierId: 123456,
      createDateTime: 1593680142109,
      lastUpdateDate: 1594382124401,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Straight Wig - Ash Blonde',
      categoryName: 'Wigs',
      description:
        'Elegant ash blonde straight wig. Cool-toned blonde perfect for modern looks.',
      quantity: 11,
      listPrice: 369.99,
      salePrice: 319.99,
      vatRate: 20,
      stockCode: 'STK-ASH-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 15,
          attributeValue: 'Ash Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (26 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 6,
          attributeValue: 'Straight',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Ash Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/8h5vuv8ruuu0uwtvrrrrrv9v7vt974602u6w',
    },
    {
      id: '9i6wvw9svvv1vxuwsssssw0w8wu085713v7x',
      approved: true,
      archived: false,
      productCode: 75984645,
      supplierId: 123456,
      createDateTime: 1593680142110,
      lastUpdateDate: 1594382124402,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Semi-Permanent Hair Color - Purple',
      categoryName: 'Hair Colors',
      description:
        'Vibrant purple semi-permanent hair color. Washes out gradually, perfect for trying bold colors.',
      quantity: 15,
      listPrice: 64.99,
      salePrice: 49.99,
      vatRate: 20,
      stockCode: 'STK-SEMI-PURPLE-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 16,
          attributeValue: 'Purple',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 14,
          attributeValue: 'Semi-Permanent',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Purple',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/9i6wvw9svvv1vxuwsssssw0w8wu085713v7x',
    },
    {
      id: '0j7xwx0twww2wyvxtttttx1x9xv196824w8y',
      approved: true,
      archived: false,
      productCode: 75984646,
      supplierId: 123456,
      createDateTime: 1593680142111,
      lastUpdateDate: 1594382124403,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Curly Bob Wig - Chocolate Brown',
      categoryName: 'Wigs',
      description:
        'Chic curly bob wig in rich chocolate brown. Perfect balance of style and manageability.',
      quantity: 12,
      listPrice: 299.99,
      salePrice: 249.99,
      vatRate: 20,
      stockCode: 'STK-CURLY-BOB-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 17,
          attributeValue: 'Chocolate Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 4,
          attributeValue: 'Short (12 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 11,
          attributeValue: 'Curly Bob',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Chocolate Brown',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/0j7xwx0twww2wyvxtttttx1x9xv196824w8y',
    },
    {
      id: '1k8yxy1uxxx3xzyuyuuuuy2y0yw207935x9z',
      approved: true,
      archived: false,
      productCode: 75984647,
      supplierId: 123456,
      createDateTime: 1593680142112,
      lastUpdateDate: 1594382124404,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Remover - Gentle Formula',
      categoryName: 'Hair Colors',
      description:
        'Gentle hair color remover. Safely removes unwanted hair color without damaging your hair.',
      quantity: 28,
      listPrice: 54.99,
      salePrice: 39.99,
      vatRate: 20,
      stockCode: 'STK-REMOVER-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Type',
          attributeValueId: 15,
          attributeValue: 'Color Remover',
        },
        {
          attributeId: 2,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'N/A',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/1k8yxy1uxxx3xzyuyuuuuy2y0yw207935x9z',
    },
    {
      id: '2l9zyz2vyyy4yazvzzzzvz3z1zx318046y0a',
      approved: true,
      archived: false,
      productCode: 75984648,
      supplierId: 123456,
      createDateTime: 1593680142113,
      lastUpdateDate: 1594382124405,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Wavy Wig - Strawberry Blonde',
      categoryName: 'Wigs',
      description:
        'Beautiful strawberry blonde wavy wig. Warm golden tones with natural wave pattern.',
      quantity: 8,
      listPrice: 349.99,
      salePrice: 299.99,
      vatRate: 20,
      stockCode: 'STK-STRAWBERRY-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 18,
          attributeValue: 'Strawberry Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 4,
          attributeValue: 'Wavy',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Strawberry Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/2l9zyz2vyyy4yazvzzzzvz3z1zx318046y0a',
    },
    {
      id: '3m0zaz3wzzz5zbawaaaaaw4w2wy429157z1b',
      approved: true,
      archived: false,
      productCode: 75984649,
      supplierId: 123456,
      createDateTime: 1593680142114,
      lastUpdateDate: 1594382124406,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Toner - Silver',
      categoryName: 'Hair Colors',
      description:
        'Silver toner for blonde hair. Neutralizes yellow tones for a cool, ashy finish.',
      quantity: 24,
      listPrice: 49.99,
      salePrice: 34.99,
      vatRate: 20,
      stockCode: 'STK-TONER-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 19,
          attributeValue: 'Silver',
        },
        {
          attributeId: 2,
          attributeName: 'Type',
          attributeValueId: 16,
          attributeValue: 'Toner',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Silver',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/3m0zaz3wzzz5zbawaaaaaw4w2wy429157z1b',
    },
    {
      id: '4n1ab4xaaa6acbxbbbbbx5x3xz530268a2c',
      approved: true,
      archived: false,
      productCode: 75984650,
      supplierId: 123456,
      createDateTime: 1593680142115,
      lastUpdateDate: 1594382124407,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Medium Length Straight Wig - Dark Blonde',
      categoryName: 'Wigs',
      description:
        'Versatile medium length straight wig in dark blonde. Perfect for everyday wear.',
      quantity: 15,
      listPrice: 279.99,
      salePrice: 229.99,
      vatRate: 20,
      stockCode: 'STK-DARK-BLONDE-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 20,
          attributeValue: 'Dark Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 3,
          attributeValue: 'Medium (18 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 6,
          attributeValue: 'Straight',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Dark Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/4n1ab4xaaa6acbxbbbbbx5x3xz530268a2c',
    },
    {
      id: '5o2bc5ybbb7bdcyccccccy6y4ya641379b3d',
      approved: true,
      archived: false,
      productCode: 75984651,
      supplierId: 123456,
      createDateTime: 1593680142116,
      lastUpdateDate: 1594382124408,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Developer - 20 Volume',
      categoryName: 'Hair Colors',
      description:
        'Professional 20 volume developer for hair coloring. Essential for permanent hair dyes.',
      quantity: 35,
      listPrice: 44.99,
      salePrice: 29.99,
      vatRate: 20,
      stockCode: 'STK-DEVELOPER-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Type',
          attributeValueId: 17,
          attributeValue: 'Developer',
        },
        {
          attributeId: 2,
          attributeName: 'Volume',
          attributeValueId: 14,
          attributeValue: '20 Volume',
        },
        {
          attributeId: 3,
          attributeName: 'Size',
          attributeValueId: 15,
          attributeValue: '500ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'N/A',
      size: '500ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/5o2bc5ybbb7bdcyccccc cy6y4ya641379b3d',
    },
    {
      id: '6p3cd6zccc8cdezddddddz7z5zb752480c4e',
      approved: true,
      archived: false,
      productCode: 75984652,
      supplierId: 123456,
      createDateTime: 1593680142117,
      lastUpdateDate: 1594382124409,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Curly Wig - Burgundy',
      categoryName: 'Wigs',
      description:
        'Rich burgundy curly wig. Deep red-purple tones with natural curl pattern.',
      quantity: 10,
      listPrice: 359.99,
      salePrice: 309.99,
      vatRate: 20,
      stockCode: 'STK-BURGUNDY-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 21,
          attributeValue: 'Burgundy',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 5,
          attributeValue: 'Curly',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Burgundy',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/6p3cd6zccc8cdezddddddz7z5zb752480c4e',
    },
    {
      id: '7q4de7add9defaeeeeeeea8a6ac863591d5f',
      approved: true,
      archived: false,
      productCode: 75984653,
      supplierId: 123456,
      createDateTime: 1593680142118,
      lastUpdateDate: 1594382124410,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Bleach Kit - Professional',
      categoryName: 'Hair Colors',
      description:
        'Professional hair bleach kit. Lightens hair up to 7 levels for dramatic color changes.',
      quantity: 16,
      listPrice: 129.99,
      salePrice: 99.99,
      vatRate: 20,
      stockCode: 'STK-BLEACH-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Type',
          attributeValueId: 18,
          attributeValue: 'Bleach Kit',
        },
        {
          attributeId: 2,
          attributeName: 'Volume',
          attributeValueId: 13,
          attributeValue: 'Full Kit',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'N/A',
      size: 'Full Kit',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/7q4de7add9defaeeeeeeea8a6ac863591d5f',
    },
    {
      id: '8r5ef8bee0efgbfaaaaaab9b7bd974602e6g',
      approved: true,
      archived: false,
      productCode: 75984654,
      supplierId: 123456,
      createDateTime: 1593680142119,
      lastUpdateDate: 1594382124411,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Short Pixie Wig - Platinum',
      categoryName: 'Wigs',
      description:
        'Bold platinum pixie cut wig. Modern and edgy style for confident individuals.',
      quantity: 7,
      listPrice: 239.99,
      salePrice: 189.99,
      vatRate: 20,
      stockCode: 'STK-PIXIE-PLATINUM-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 7,
          attributeValue: 'Platinum Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 5,
          attributeValue: 'Very Short (6 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 9,
          attributeValue: 'Pixie',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Platinum Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/8r5ef8bee0efgbfaaaaaab9b7bd974602e6g',
    },
    {
      id: '9s6fg9cff1fghcgbbbbbbc0c8ce085713f7h',
      approved: true,
      archived: false,
      productCode: 75984655,
      supplierId: 123456,
      createDateTime: 1593680142120,
      lastUpdateDate: 1594382124412,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Gloss - Clear Shine',
      categoryName: 'Hair Colors',
      description:
        'Clear hair gloss for added shine and protection. Enhances natural hair color.',
      quantity: 32,
      listPrice: 39.99,
      salePrice: 29.99,
      vatRate: 20,
      stockCode: 'STK-GLOSS-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Type',
          attributeValueId: 19,
          attributeValue: 'Hair Gloss',
        },
        {
          attributeId: 2,
          attributeName: 'Color',
          attributeValueId: 22,
          attributeValue: 'Clear',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 11,
          attributeValue: '100ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Clear',
      size: '100ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/9s6fg9cff1fghcgbbbbbbc0c8ce085713f7h',
    },
    {
      id: '0t7gh0dgg2ghidhccccccd1d9df196824g8i',
      approved: true,
      archived: false,
      productCode: 75984656,
      supplierId: 123456,
      createDateTime: 1593680142121,
      lastUpdateDate: 1594382124413,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Straight Wig - Chestnut Brown',
      categoryName: 'Wigs',
      description:
        'Elegant chestnut brown straight wig. Rich brown with warm red undertones.',
      quantity: 14,
      listPrice: 329.99,
      salePrice: 279.99,
      vatRate: 20,
      stockCode: 'STK-CHESTNUT-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 23,
          attributeValue: 'Chestnut Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (26 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 6,
          attributeValue: 'Straight',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Chestnut Brown',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/0t7gh0dgg2ghidhccccccd1d9df196824g8i',
    },
    {
      id: '1u8hi1ehh3hijeiddddde2e0eg207935h9j',
      approved: true,
      archived: false,
      productCode: 75984657,
      supplierId: 123456,
      createDateTime: 1593680142122,
      lastUpdateDate: 1594382124414,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Conditioner - Color Protect',
      categoryName: 'Hair Colors',
      description:
        'Color-protecting conditioner. Extends the life of your hair color while keeping it soft.',
      quantity: 40,
      listPrice: 34.99,
      salePrice: 24.99,
      vatRate: 20,
      stockCode: 'STK-CONDITIONER-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Type',
          attributeValueId: 20,
          attributeValue: 'Conditioner',
        },
        {
          attributeId: 2,
          attributeName: 'Volume',
          attributeValueId: 16,
          attributeValue: '250ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'N/A',
      size: '250ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/1u8hi1ehh3hijeiddddde2e0eg207935h9j',
    },
    {
      id: '2v9ij2fii4ijkfjfeeeeef3f1fh318046i0k',
      approved: true,
      archived: false,
      productCode: 75984658,
      supplierId: 123456,
      createDateTime: 1593680142123,
      lastUpdateDate: 1594382124415,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Wavy Bob Wig - Light Brown',
      categoryName: 'Wigs',
      description:
        'Chic wavy bob in light brown. Perfect for a fresh, modern look.',
      quantity: 13,
      listPrice: 289.99,
      salePrice: 239.99,
      vatRate: 20,
      stockCode: 'STK-WAVY-BOB-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 24,
          attributeValue: 'Light Brown',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 4,
          attributeValue: 'Short (12 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 12,
          attributeValue: 'Wavy Bob',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Light Brown',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/2v9ij2fii4ijkfjfeeeeef3f1fh318046i0k',
    },
    {
      id: '3w0jk3gjj5jklgkgfffffg4g2gi429157j1l',
      approved: true,
      archived: false,
      productCode: 75984659,
      supplierId: 123456,
      createDateTime: 1593680142124,
      lastUpdateDate: 1594382124416,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Hair Color Shampoo - Purple Toning',
      categoryName: 'Hair Colors',
      description:
        'Purple toning shampoo for blonde hair. Neutralizes brassy tones between color treatments.',
      quantity: 27,
      listPrice: 42.99,
      salePrice: 32.99,
      vatRate: 20,
      stockCode: 'STK-PURPLE-SHAMPOO-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Type',
          attributeValueId: 21,
          attributeValue: 'Toning Shampoo',
        },
        {
          attributeId: 2,
          attributeName: 'Color',
          attributeValueId: 16,
          attributeValue: 'Purple',
        },
        {
          attributeId: 3,
          attributeName: 'Volume',
          attributeValueId: 16,
          attributeValue: '250ml',
        },
      ],
      hasActiveCampaign: true,
      locked: false,
      color: 'Purple',
      size: '250ml',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/3w0jk3gjj5jkl gkgfffffg4g2gi429157j1l',
    },
    {
      id: '4x1kl4hkk6klm hlhgggggh5h3hj530268k2m',
      approved: true,
      archived: false,
      productCode: 75984660,
      supplierId: 123456,
      createDateTime: 1593680142125,
      lastUpdateDate: 1594382124417,
      gender: 'Female',
      brand: 'Atlas Premium',
      title: 'Long Layered Wig - Golden Blonde',
      categoryName: 'Wigs',
      description:
        'Beautiful golden blonde layered wig. Adds volume and movement with natural-looking layers.',
      quantity: 11,
      listPrice: 379.99,
      salePrice: 329.99,
      vatRate: 20,
      stockCode: 'STK-GOLDEN-001',
      images: [
        {
          url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500',
        },
      ],
      attributes: [
        {
          attributeId: 1,
          attributeName: 'Color',
          attributeValueId: 25,
          attributeValue: 'Golden Blonde',
        },
        {
          attributeId: 2,
          attributeName: 'Length',
          attributeValueId: 2,
          attributeValue: 'Long (24 inches)',
        },
        {
          attributeId: 3,
          attributeName: 'Material',
          attributeValueId: 3,
          attributeValue: 'Synthetic Fiber',
        },
        {
          attributeId: 4,
          attributeName: 'Style',
          attributeValueId: 10,
          attributeValue: 'Layered Wavy',
        },
      ],
      hasActiveCampaign: false,
      locked: false,
      color: 'Golden Blonde',
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: true,
      productUrl: '/product/4x1kl4hkk6klm hlhgggggh5h3hj530268k2m',
    },
    // African Afro Hair Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `african-afro-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 80000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Premium', 'Afro Elite', 'Natural Curls', 'African Heritage'][i % 4],
      barcode: `8690${String(80000000 + i).padStart(9, '0')}`,
      title: [
        'Premium African Afro Hair - Natural Texture',
        'Curly African Afro Hair - Voluminous',
        'Kinky African Afro Hair - Authentic',
        'Coily African Afro Hair - Professional',
        'Tight Curl African Afro Hair - Classic'
      ][i % 5] + ` ${['12"', '14"', '16"', '18"', '20"', '22"', '24"'][i % 7]}`,
      categoryName: 'African Afro Hair',
      productMainId: `AAH${String(i + 1).padStart(3, '0')}`,
      description: `Premium quality African afro hair with natural texture. ${['Perfect for braiding', 'Ideal for extensions', 'Great for styling', 'Excellent for weaving'][i % 4]}. Made from 100% human hair.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 20) + 5,
      listPrice: [199.99, 249.99, 299.99, 349.99, 399.99][i % 5],
      salePrice: [149.99, 199.99, 249.99, 299.99, 349.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.3 + (i % 3) * 0.1,
      stockCode: `STK-AAH-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-AAH-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [2, 3, 4, 5][i % 4],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Color', attributeValueId: i % 10 + 1, attributeValue: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Auburn', 'Burgundy', 'Honey', 'Caramel', 'Blonde', 'Mixed'][i % 10] },
        { attributeId: 2, attributeName: 'Length', attributeValueId: i % 7 + 1, attributeValue: ['12"', '14"', '16"', '18"', '20"', '22"', '24"'][i % 7] },
        { attributeId: 3, attributeName: 'Texture', attributeValueId: i % 4 + 1, attributeValue: ['Kinky', 'Coily', 'Curly', 'Tight Curl'][i % 4] },
      ],
      platformListingId: `PLT-AAH-${i + 1}`,
      stockId: `STK-AAH-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 2000 + i,
      pimCategoryId: 600 + i,
      brandId: 300 + (i % 5),
      version: 1,
      color: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Auburn'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/african-afro-${i + 1}`,
    })),
    // Russian Afro Hair Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `russian-afro-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 81000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Premium', 'Russian Elite', 'Slavic Hair', 'Premium Russian'][i % 4],
      barcode: `8690${String(81000000 + i).padStart(9, '0')}`,
      title: [
        'Premium Russian Afro Hair - Soft Texture',
        'Silky Russian Afro Hair - Luxurious',
        'Fine Russian Afro Hair - Natural',
        'Smooth Russian Afro Hair - Professional',
        'Straight Russian Afro Hair - Classic'
      ][i % 5] + ` ${['14"', '16"', '18"', '20"', '22"', '24"', '26"'][i % 7]}`,
      categoryName: 'Russian Afro Hair',
      productMainId: `RAH${String(i + 1).padStart(3, '0')}`,
      description: `Premium quality Russian afro hair with soft texture. ${['Perfect for extensions', 'Ideal for weaving', 'Great for styling', 'Excellent for braiding'][i % 4]}. Made from 100% human hair.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 20) + 5,
      listPrice: [249.99, 299.99, 349.99, 399.99, 449.99][i % 5],
      salePrice: [199.99, 249.99, 299.99, 349.99, 399.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.3 + (i % 3) * 0.1,
      stockCode: `STK-RAH-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-RAH-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [2, 3, 4, 5][i % 4],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 1000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Color', attributeValueId: i % 10 + 1, attributeValue: ['Blonde', 'Light Brown', 'Brown', 'Dark Brown', 'Black', 'Auburn', 'Honey', 'Caramel', 'Platinum', 'Strawberry'][i % 10] },
        { attributeId: 2, attributeName: 'Length', attributeValueId: i % 7 + 1, attributeValue: ['14"', '16"', '18"', '20"', '22"', '24"', '26"'][i % 7] },
        { attributeId: 3, attributeName: 'Texture', attributeValueId: i % 3 + 1, attributeValue: ['Straight', 'Wavy', 'Curly'][i % 3] },
      ],
      platformListingId: `PLT-RAH-${i + 1}`,
      stockId: `STK-RAH-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 3000 + i,
      pimCategoryId: 700 + i,
      brandId: 400 + (i % 5),
      version: 1,
      color: ['Blonde', 'Light Brown', 'Brown', 'Dark Brown', 'Black'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/russian-afro-${i + 1}`,
    })),
    // Training Mannequins Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `training-mannequin-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 82000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Unisex',
      brand: ['Atlas Training', 'Professional Mannequin', 'Hair Academy', 'Training Pro'][i % 4],
      barcode: `8690${String(82000000 + i).padStart(9, '0')}`,
      title: [
        'Professional Training Mannequin Head',
        'Hair Styling Training Mannequin',
        'Cosmetology Training Mannequin',
        'Advanced Training Mannequin Head',
        'Premium Training Mannequin'
      ][i % 5] + ` ${['Standard', 'Large', 'Extra Large', 'Small'][i % 4]}`,
      categoryName: 'Training Mannequins',
      productMainId: `TM${String(i + 1).padStart(3, '0')}`,
      description: `Professional training mannequin head for ${['hair styling', 'cosmetology training', 'hair cutting', 'coloring practice'][i % 4]}. ${['Durable construction', 'Realistic hair', 'Easy to use', 'Professional quality'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 30) + 10,
      listPrice: [79.99, 99.99, 119.99, 149.99, 179.99][i % 5],
      salePrice: [59.99, 79.99, 99.99, 119.99, 149.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 1.5 + (i % 3) * 0.5,
      stockCode: `STK-TM-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-TM-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [3, 4, 5, 6][i % 4],
        fastDeliveryType: i % 4 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 2000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Size', attributeValueId: i % 4 + 1, attributeValue: ['Small', 'Standard', 'Large', 'Extra Large'][i % 4] },
        { attributeId: 2, attributeName: 'Hair Type', attributeValueId: i % 3 + 1, attributeValue: ['Synthetic', 'Human Hair', 'Mixed'][i % 3] },
        { attributeId: 3, attributeName: 'Color', attributeValueId: i % 5 + 1, attributeValue: ['Blonde', 'Brown', 'Black', 'Auburn', 'Mixed'][i % 5] },
      ],
      platformListingId: `PLT-TM-${i + 1}`,
      stockId: `STK-TM-${i + 1}`,
      hasActiveCampaign: i % 4 === 0,
      locked: false,
      productContentId: 4000 + i,
      pimCategoryId: 800 + i,
      brandId: 500 + (i % 5),
      version: 1,
      color: ['Blonde', 'Brown', 'Black', 'Auburn', 'Mixed'][i % 5],
      size: ['Small', 'Standard', 'Large', 'Extra Large'][i % 4],
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/training-mannequin-${i + 1}`,
    })),
    // Hair Accessories Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `hair-accessory-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 83000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Accessories', 'Hair Elegance', 'Style Pro', 'Accessory Plus'][i % 4],
      barcode: `8690${String(83000000 + i).padStart(9, '0')}`,
      title: [
        'Hair Clips Set - Decorative',
        'Hair Pins - Professional',
        'Hair Bands - Elastic',
        'Hair Combs - Styling',
        'Hair Barrettes - Fashion'
      ][i % 5] + ` ${['Gold', 'Silver', 'Black', 'Colorful', 'Pearl'][i % 5]}`,
      categoryName: 'Hair Accessories',
      productMainId: `HA${String(i + 1).padStart(3, '0')}`,
      description: `Beautiful hair accessories for ${['everyday styling', 'special occasions', 'professional use', 'fashion statements'][i % 4]}. ${['High quality materials', 'Durable construction', 'Elegant design', 'Comfortable to wear'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 50) + 20,
      listPrice: [9.99, 14.99, 19.99, 24.99, 29.99][i % 5],
      salePrice: [7.99, 11.99, 15.99, 19.99, 24.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.1 + (i % 2) * 0.05,
      stockCode: `STK-HA-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-HA-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [1, 2, 3][i % 3],
        fastDeliveryType: i % 2 === 0 ? ('SAME_DAY_SHIPPING' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 3000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Type', attributeValueId: i % 5 + 1, attributeValue: ['Clips', 'Pins', 'Bands', 'Combs', 'Barrettes'][i % 5] },
        { attributeId: 2, attributeName: 'Color', attributeValueId: i % 8 + 1, attributeValue: ['Gold', 'Silver', 'Black', 'White', 'Red', 'Blue', 'Pink', 'Pearl'][i % 8] },
        { attributeId: 3, attributeName: 'Material', attributeValueId: i % 4 + 1, attributeValue: ['Metal', 'Plastic', 'Fabric', 'Mixed'][i % 4] },
      ],
      platformListingId: `PLT-HA-${i + 1}`,
      stockId: `STK-HA-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 5000 + i,
      pimCategoryId: 900 + i,
      brandId: 600 + (i % 5),
      version: 1,
      color: ['Gold', 'Silver', 'Black', 'White', 'Colorful'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/hair-accessory-${i + 1}`,
    })),
    // Hair Extension Materials Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `extension-material-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 84000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Materials', 'Extension Pro', 'Hair Materials', 'Professional Supply'][i % 4],
      barcode: `8690${String(84000000 + i).padStart(9, '0')}`,
      title: [
        'Hair Extension Tape - Double Sided',
        'Hair Extension Glue - Professional',
        'Hair Extension Thread - Strong',
        'Hair Extension Clips - Secure',
        'Hair Extension Rings - Micro'
      ][i % 5] + ` ${['Clear', 'Black', 'Brown', 'Transparent'][i % 4]}`,
      categoryName: 'Hair Extension Materials',
      productMainId: `HEM${String(i + 1).padStart(3, '0')}`,
      description: `Professional hair extension materials for ${['tape-in extensions', 'glue-in extensions', 'clip-in extensions', 'micro ring extensions'][i % 4]}. ${['High quality', 'Long lasting', 'Easy to use', 'Professional grade'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 100) + 50,
      listPrice: [12.99, 19.99, 24.99, 29.99, 34.99][i % 5],
      salePrice: [9.99, 15.99, 19.99, 24.99, 29.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.2 + (i % 3) * 0.1,
      stockCode: `STK-HEM-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-HEM-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [2, 3, 4][i % 3],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 4000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Type', attributeValueId: i % 5 + 1, attributeValue: ['Tape', 'Glue', 'Thread', 'Clips', 'Rings'][i % 5] },
        { attributeId: 2, attributeName: 'Color', attributeValueId: i % 4 + 1, attributeValue: ['Clear', 'Black', 'Brown', 'Transparent'][i % 4] },
        { attributeId: 3, attributeName: 'Size', attributeValueId: i % 3 + 1, attributeValue: ['Small', 'Medium', 'Large'][i % 3] },
      ],
      platformListingId: `PLT-HEM-${i + 1}`,
      stockId: `STK-HEM-${i + 1}`,
      hasActiveCampaign: i % 4 === 0,
      locked: false,
      productContentId: 6000 + i,
      pimCategoryId: 1000 + i,
      brandId: 700 + (i % 5),
      version: 1,
      color: ['Clear', 'Black', 'Brown', 'Transparent'][i % 4],
      size: ['Small', 'Medium', 'Large'][i % 3],
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/extension-material-${i + 1}`,
    })),
    // Wig Materials Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `wig-material-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 85000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Unisex',
      brand: ['Atlas Materials', 'Wig Pro', 'Professional Materials', 'Wig Supply'][i % 4],
      barcode: `8690${String(85000000 + i).padStart(9, '0')}`,
      title: [
        'Wig Cap - Nylon',
        'Wig Cap - Mesh',
        'Wig Lace - Swiss',
        'Wig Lace - French',
        'Wig Base - Monofilament'
      ][i % 5] + ` ${['Beige', 'Black', 'Brown', 'Transparent'][i % 4]}`,
      categoryName: 'Wig Materials',
      productMainId: `WM${String(i + 1).padStart(3, '0')}`,
      description: `Professional wig making materials for ${['wig construction', 'wig repair', 'wig customization', 'wig maintenance'][i % 4]}. ${['High quality', 'Durable', 'Professional grade', 'Easy to work with'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 80) + 40,
      listPrice: [15.99, 24.99, 34.99, 44.99, 54.99][i % 5],
      salePrice: [12.99, 19.99, 29.99, 39.99, 49.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.15 + (i % 2) * 0.1,
      stockCode: `STK-WM-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-WM-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [2, 3, 4][i % 3],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 5000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Type', attributeValueId: i % 5 + 1, attributeValue: ['Cap', 'Lace', 'Base', 'Mesh', 'Net'][i % 5] },
        { attributeId: 2, attributeName: 'Color', attributeValueId: i % 4 + 1, attributeValue: ['Beige', 'Black', 'Brown', 'Transparent'][i % 4] },
        { attributeId: 3, attributeName: 'Material', attributeValueId: i % 4 + 1, attributeValue: ['Nylon', 'Mesh', 'Lace', 'Monofilament'][i % 4] },
      ],
      platformListingId: `PLT-WM-${i + 1}`,
      stockId: `STK-WM-${i + 1}`,
      hasActiveCampaign: i % 4 === 0,
      locked: false,
      productContentId: 7000 + i,
      pimCategoryId: 1100 + i,
      brandId: 800 + (i % 5),
      version: 1,
      color: ['Beige', 'Black', 'Brown', 'Transparent'][i % 4],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/wig-material-${i + 1}`,
    })),
    // Bead Extensions Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `bead-extension-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 86000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Extensions', 'Bead Pro', 'Extension Elite', 'Bead Master'][i % 4],
      barcode: `8690${String(86000000 + i).padStart(9, '0')}`,
      title: [
        'Bead Extension Hair - Premium',
        'Bead Extension Weft - Professional',
        'Bead Extension Bundle - Natural',
        'Bead Extension Pack - Complete',
        'Bead Extension Set - Deluxe'
      ][i % 5] + ` ${['12"', '14"', '16"', '18"', '20"', '22"', '24"'][i % 7]}`,
      categoryName: 'Bead Extensions',
      productMainId: `BE${String(i + 1).padStart(3, '0')}`,
      description: `Premium bead extension hair for ${['natural look', 'long-lasting style', 'easy maintenance', 'professional results'][i % 4]}. ${['100% human hair', 'High quality', 'Easy to install', 'Durable'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 25) + 10,
      listPrice: [179.99, 229.99, 279.99, 329.99, 379.99][i % 5],
      salePrice: [149.99, 199.99, 249.99, 299.99, 349.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.4 + (i % 3) * 0.1,
      stockCode: `STK-BE-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-BE-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [3, 4, 5][i % 3],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 6000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Color', attributeValueId: i % 10 + 1, attributeValue: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Blonde', 'Auburn', 'Burgundy', 'Honey', 'Caramel', 'Mixed'][i % 10] },
        { attributeId: 2, attributeName: 'Length', attributeValueId: i % 7 + 1, attributeValue: ['12"', '14"', '16"', '18"', '20"', '22"', '24"'][i % 7] },
        { attributeId: 3, attributeName: 'Type', attributeValueId: i % 3 + 1, attributeValue: ['Weft', 'Bundle', 'Pack'][i % 3] },
      ],
      platformListingId: `PLT-BE-${i + 1}`,
      stockId: `STK-BE-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 8000 + i,
      pimCategoryId: 1200 + i,
      brandId: 900 + (i % 5),
      version: 1,
      color: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Blonde'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/bead-extension-${i + 1}`,
    })),
    // Micro Extensions Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `micro-extension-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 87000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Micro', 'Micro Pro', 'Extension Elite', 'Micro Master'][i % 4],
      barcode: `8690${String(87000000 + i).padStart(9, '0')}`,
      title: [
        'Micro Extension Hair - Premium',
        'Micro Ring Extension - Professional',
        'Micro Extension Weft - Natural',
        'Micro Extension Bundle - Complete',
        'Micro Extension Set - Deluxe'
      ][i % 5] + ` ${['14"', '16"', '18"', '20"', '22"', '24"', '26"'][i % 7]}`,
      categoryName: 'Micro Extensions',
      productMainId: `ME${String(i + 1).padStart(3, '0')}`,
      description: `Premium micro extension hair for ${['seamless blending', 'natural appearance', 'easy maintenance', 'long-lasting style'][i % 4]}. ${['100% human hair', 'High quality', 'Easy installation', 'Professional results'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 25) + 10,
      listPrice: [199.99, 249.99, 299.99, 349.99, 399.99][i % 5],
      salePrice: [169.99, 219.99, 269.99, 319.99, 369.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.4 + (i % 3) * 0.1,
      stockCode: `STK-ME-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-ME-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [3, 4, 5][i % 3],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 7000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Color', attributeValueId: i % 10 + 1, attributeValue: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Blonde', 'Auburn', 'Burgundy', 'Honey', 'Caramel', 'Mixed'][i % 10] },
        { attributeId: 2, attributeName: 'Length', attributeValueId: i % 7 + 1, attributeValue: ['14"', '16"', '18"', '20"', '22"', '24"', '26"'][i % 7] },
        { attributeId: 3, attributeName: 'Type', attributeValueId: i % 3 + 1, attributeValue: ['Weft', 'Bundle', 'Pack'][i % 3] },
      ],
      platformListingId: `PLT-ME-${i + 1}`,
      stockId: `STK-ME-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 9000 + i,
      pimCategoryId: 1300 + i,
      brandId: 1000 + (i % 5),
      version: 1,
      color: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Blonde'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/micro-extension-${i + 1}`,
    })),
    // Hairpieces Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `hairpiece-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 88000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Hairpieces', 'Hairpiece Pro', 'Elegant Pieces', 'Hairpiece Elite'][i % 4],
      barcode: `8690${String(88000000 + i).padStart(9, '0')}`,
      title: [
        'Hairpiece - Clip-In',
        'Hairpiece - Ponytail',
        'Hairpiece - Bun',
        'Hairpiece - Fringe',
        'Hairpiece - Topper'
      ][i % 5] + ` ${['Blonde', 'Brown', 'Black', 'Auburn', 'Mixed'][i % 5]}`,
      categoryName: 'Hairpieces',
      productMainId: `HP${String(i + 1).padStart(3, '0')}`,
      description: `Beautiful hairpiece for ${['instant volume', 'quick styling', 'special occasions', 'everyday wear'][i % 4]}. ${['100% human hair', 'High quality', 'Easy to attach', 'Natural look'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 20) + 8,
      listPrice: [89.99, 119.99, 149.99, 179.99, 209.99][i % 5],
      salePrice: [69.99, 99.99, 129.99, 159.99, 189.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.3 + (i % 2) * 0.1,
      stockCode: `STK-HP-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-HP-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [2, 3, 4][i % 3],
        fastDeliveryType: i % 2 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 8000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Type', attributeValueId: i % 5 + 1, attributeValue: ['Clip-In', 'Ponytail', 'Bun', 'Fringe', 'Topper'][i % 5] },
        { attributeId: 2, attributeName: 'Color', attributeValueId: i % 8 + 1, attributeValue: ['Blonde', 'Light Brown', 'Brown', 'Dark Brown', 'Black', 'Auburn', 'Burgundy', 'Mixed'][i % 8] },
        { attributeId: 3, attributeName: 'Length', attributeValueId: i % 4 + 1, attributeValue: ['Short', 'Medium', 'Long', 'Extra Long'][i % 4] },
      ],
      platformListingId: `PLT-HP-${i + 1}`,
      stockId: `STK-HP-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 10000 + i,
      pimCategoryId: 1400 + i,
      brandId: 1100 + (i % 5),
      version: 1,
      color: ['Blonde', 'Brown', 'Black', 'Auburn', 'Mixed'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/hairpiece-${i + 1}`,
    })),
    // Synthetic Tresses Products (50+)
    ...Array.from({ length: 50 }, (_, i) => ({
      id: `synthetic-tress-${i + 1}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      approved: true,
      archived: false,
      productCode: 89000000 + i,
      supplierId: 123456,
      createDateTime: Date.now() - (i * 86400000),
      lastUpdateDate: Date.now() - (i * 86400000),
      gender: 'Female',
      brand: ['Atlas Synthetic', 'Tress Pro', 'Synthetic Elite', 'Tress Master'][i % 4],
      barcode: `8690${String(89000000 + i).padStart(9, '0')}`,
      title: [
        'Synthetic Tress - Wavy',
        'Synthetic Tress - Curly',
        'Synthetic Tress - Straight',
        'Synthetic Tress - Kinky',
        'Synthetic Tress - Body Wave'
      ][i % 5] + ` ${['12"', '14"', '16"', '18"', '20"', '22"', '24"'][i % 7]}`,
      categoryName: 'Synthetic Tresses',
      productMainId: `ST${String(i + 1).padStart(3, '0')}`,
      description: `Premium synthetic tress for ${['braiding', 'weaving', 'extensions', 'styling'][i % 4]}. ${['Heat resistant', 'Easy to style', 'Long lasting', 'Natural look'][i % 4]}.`,
      stockUnitType: 'PIECE',
      quantity: Math.floor(Math.random() * 30) + 15,
      listPrice: [39.99, 49.99, 59.99, 69.99, 79.99][i % 5],
      salePrice: [29.99, 39.99, 49.99, 59.99, 69.99][i % 5],
      vatRate: 20,
      dimensionalWeight: 0.25 + (i % 2) * 0.1,
      stockCode: `STK-ST-${String(i + 1).padStart(3, '0')}`,
      locationBasedDelivery: 'ENABLED' as const,
      lotNumber: `LOT-ST-2024-${String(i + 1).padStart(3, '0')}`,
      deliveryOption: {
        deliveryDuration: [2, 3, 4][i % 3],
        fastDeliveryType: i % 3 === 0 ? ('FAST_DELIVERY' as const) : null,
      },
      images: [{
        url: `https://images.unsplash.com/photo-${1500000000000 + i + 9000}?w=500`,
      }],
      attributes: [
        { attributeId: 1, attributeName: 'Style', attributeValueId: i % 5 + 1, attributeValue: ['Wavy', 'Curly', 'Straight', 'Kinky', 'Body Wave'][i % 5] },
        { attributeId: 2, attributeName: 'Length', attributeValueId: i % 7 + 1, attributeValue: ['12"', '14"', '16"', '18"', '20"', '22"', '24"'][i % 7] },
        { attributeId: 3, attributeName: 'Color', attributeValueId: i % 8 + 1, attributeValue: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Blonde', 'Auburn', 'Burgundy', 'Mixed'][i % 8] },
      ],
      platformListingId: `PLT-ST-${i + 1}`,
      stockId: `STK-ST-${i + 1}`,
      hasActiveCampaign: i % 3 === 0,
      locked: false,
      productContentId: 11000 + i,
      pimCategoryId: 1500 + i,
      brandId: 1200 + (i % 5),
      version: 1,
      color: ['Black', 'Dark Brown', 'Brown', 'Light Brown', 'Blonde'][i % 5],
      size: 'One Size',
      lockedByUnSuppliedReason: false,
      onsale: i % 2 === 0,
      productUrl: `/product/synthetic-tress-${i + 1}`,
    })),
  ];

  getProducts(
    page: number = 0,
    size: number = 10
  ): Observable<ProductListResponse> {
    const start = page * size;
    const end = start + size;
    const paginatedProducts = this.dummyProducts.slice(start, end);

    return of({
      totalElements: this.dummyProducts.length,
      totalPages: Math.ceil(this.dummyProducts.length / size),
      page: page,
      size: size,
      content: paginatedProducts,
    }).pipe(); // Simulate API delay
  }

  getProductById(id: string): Observable<ProductResponse | null> {
    const product = this.dummyProducts.find((p) => p.id === id);
    return of(product || null).pipe();
  }

  getProductsByCategory(
    categoryName: string,
    page: number = 0,
    size: number = 10
  ): Observable<ProductListResponse> {
    const filteredProducts = this.dummyProducts.filter(
      (p) => p.categoryName?.toLowerCase() === categoryName.toLowerCase()
    );
    const start = page * size;
    const end = start + size;
    const paginatedProducts = filteredProducts.slice(start, end);

    return of({
      totalElements: filteredProducts.length,
      totalPages: Math.ceil(filteredProducts.length / size),
      page: page,
      size: size,
      content: paginatedProducts,
    }).pipe();
  }

  getProductsByColor(
    color: string,
    page: number = 0,
    size: number = 10
  ): Observable<ProductListResponse> {
    const filteredProducts = this.dummyProducts.filter((p) =>
      p.color?.toLowerCase().includes(color.toLowerCase())
    );
    const start = page * size;
    const end = start + size;
    const paginatedProducts = filteredProducts.slice(start, end);

    return of({
      totalElements: filteredProducts.length,
      totalPages: Math.ceil(filteredProducts.length / size),
      page: page,
      size: size,
      content: paginatedProducts,
    }).pipe();
  }
}
